package social_network_system;


/**
* social_network_system/_CoordinatorStub.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from coordinator.idl
* Tuesday, April 16, 2013 12:38:51 AM IRDT
*/

public class _CoordinatorStub extends org.omg.CORBA.portable.ObjectImpl implements social_network_system.Coordinator
{

  public String login (String username, String groupname, String groupass)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("login", true);
                $out.write_string (username);
                $out.write_string (groupname);
                $out.write_string (groupass);
                $in = _invoke ($out);
                String $result = $in.read_string ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return login (username, groupname, groupass        );
            } finally {
                _releaseReply ($in);
            }
  } // login

  public String join (String name, String username, String groupname)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("join", true);
                $out.write_string (name);
                $out.write_string (username);
                $out.write_string (groupname);
                $in = _invoke ($out);
                String $result = $in.read_string ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return join (name, username, groupname        );
            } finally {
                _releaseReply ($in);
            }
  } // join

  public String answer (String username, String newusername, String groupname, String answer)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("answer", true);
                $out.write_string (username);
                $out.write_string (newusername);
                $out.write_string (groupname);
                $out.write_string (answer);
                $in = _invoke ($out);
                String $result = $in.read_string ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return answer (username, newusername, groupname, answer        );
            } finally {
                _releaseReply ($in);
            }
  } // answer

  public String getcoordinator (String username, String groupname, String grouppass)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("getcoordinator", true);
                $out.write_string (username);
                $out.write_string (groupname);
                $out.write_string (grouppass);
                $in = _invoke ($out);
                String $result = $in.read_string ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return getcoordinator (username, groupname, grouppass        );
            } finally {
                _releaseReply ($in);
            }
  } // getcoordinator

  public String leave (String username, String groupname, String grouppass)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("leave", true);
                $out.write_string (username);
                $out.write_string (groupname);
                $out.write_string (grouppass);
                $in = _invoke ($out);
                String $result = $in.read_string ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return leave (username, groupname, grouppass        );
            } finally {
                _releaseReply ($in);
            }
  } // leave

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:social_network_system/Coordinator:1.0"};

  public String[] _ids ()
  {
    return (String[])__ids.clone ();
  }

  private void readObject (java.io.ObjectInputStream s) throws java.io.IOException
  {
     String str = s.readUTF ();
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init (args, props);
   try {
     org.omg.CORBA.Object obj = orb.string_to_object (str);
     org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl) obj)._get_delegate ();
     _set_delegate (delegate);
   } finally {
     orb.destroy() ;
   }
  }

  private void writeObject (java.io.ObjectOutputStream s) throws java.io.IOException
  {
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init (args, props);
   try {
     String str = orb.object_to_string (this);
     s.writeUTF (str);
   } finally {
     orb.destroy() ;
   }
  }
} // class _CoordinatorStub
