package social_network_system;


/**
* social_network_system/Coordinator.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from coordinator.idl
* Tuesday, April 16, 2013 12:38:51 AM IRDT
*/

public interface Coordinator extends CoordinatorOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Coordinator
