package social_network_system;


/**
* social_network_system/CoordinatorOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from coordinator.idl
* Tuesday, April 16, 2013 12:38:51 AM IRDT
*/

public interface CoordinatorOperations 
{
  String login (String username, String groupname, String groupass);
  String join (String name, String username, String groupname);
  String answer (String username, String newusername, String groupname, String answer);
  String getcoordinator (String username, String groupname, String grouppass);
  String leave (String username, String groupname, String grouppass);
} // interface CoordinatorOperations
