package social_network_system;

/**
* social_network_system/CoordinatorHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from coordinator.idl
* Tuesday, April 16, 2013 12:38:51 AM IRDT
*/

public final class CoordinatorHolder implements org.omg.CORBA.portable.Streamable
{
  public social_network_system.Coordinator value = null;

  public CoordinatorHolder ()
  {
  }

  public CoordinatorHolder (social_network_system.Coordinator initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = social_network_system.CoordinatorHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    social_network_system.CoordinatorHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return social_network_system.CoordinatorHelper.type ();
  }

}
