package social_network_system;


/**
* social_network_system/DMessageOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from DMessage.idl
* Sunday, April 7, 2013 10:29:37 PM IRDT
*/

public interface DMessageOperations 
{
  void GetUniMessage (String message, String sender);
  void GetGroupMessage (String message, String sender);
} // interface DMessageOperations
