package social_network_system;

/**
* social_network_system/DMessageHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from DMessage.idl
* Sunday, April 7, 2013 10:29:37 PM IRDT
*/

public final class DMessageHolder implements org.omg.CORBA.portable.Streamable
{
  public social_network_system.DMessage value = null;

  public DMessageHolder ()
  {
  }

  public DMessageHolder (social_network_system.DMessage initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = social_network_system.DMessageHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    social_network_system.DMessageHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return social_network_system.DMessageHelper.type ();
  }

}
