package social_network_system;


/**
* social_network_system/DMessage.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from DMessage.idl
* Sunday, April 7, 2013 10:29:37 PM IRDT
*/

public interface DMessage extends DMessageOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface DMessage
