package social_network_system;


/**
* social_network_system/DMessagePOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from DMessage.idl
* Sunday, April 7, 2013 10:29:37 PM IRDT
*/

public abstract class DMessagePOA extends org.omg.PortableServer.Servant
 implements social_network_system.DMessageOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("GetUniMessage", new java.lang.Integer (0));
    _methods.put ("GetGroupMessage", new java.lang.Integer (1));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // social_network_system/DMessage/GetUniMessage
       {
         String message = in.read_string ();
         String sender = in.read_string ();
         this.GetUniMessage (message, sender);
         out = $rh.createReply();
         break;
       }

       case 1:  // social_network_system/DMessage/GetGroupMessage
       {
         String message = in.read_string ();
         String sender = in.read_string ();
         this.GetGroupMessage (message, sender);
         out = $rh.createReply();
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:social_network_system/DMessage:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public DMessage _this() 
  {
    return DMessageHelper.narrow(
    super._this_object());
  }

  public DMessage _this(org.omg.CORBA.ORB orb) 
  {
    return DMessageHelper.narrow(
    super._this_object(orb));
  }


} // class DMessagePOA
