package social_network_system;


/**
* social_network_system/Social_Network.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Social_Network.idl
* Saturday, March 30, 2013 1:35:55 AM IRDT
*/

public interface Social_Network extends Social_NetworkOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Social_Network
