package social_network_system;


/**
* social_network_system/Social_NetworkPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Social_Network.idl
* Saturday, March 30, 2013 1:35:55 AM IRDT
*/

public abstract class Social_NetworkPOA extends org.omg.PortableServer.Servant
 implements social_network_system.Social_NetworkOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("sregister", new java.lang.Integer (0));
    _methods.put ("Gcreate", new java.lang.Integer (1));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {

  //string login(in string username ,in string groupname , in string groupass);
       case 0:  // social_network_system/Social_Network/sregister
       {
         String user = in.read_string ();
         String username = in.read_string ();
         String $result = null;
         $result = this.sregister (user, username);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 1:  // social_network_system/Social_Network/Gcreate
       {
         String username = in.read_string ();
         String password = in.read_string ();
         String groupname = in.read_string ();
         String $result = null;
         $result = this.Gcreate (username, password, groupname);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:social_network_system/Social_Network:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public Social_Network _this() 
  {
    return Social_NetworkHelper.narrow(
    super._this_object());
  }

  public Social_Network _this(org.omg.CORBA.ORB orb) 
  {
    return Social_NetworkHelper.narrow(
    super._this_object(orb));
  }


} // class Social_NetworkPOA
