package social_network_system;

/**
* social_network_system/Social_NetworkHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Social_Network.idl
* Saturday, March 30, 2013 1:35:55 AM IRDT
*/

public final class Social_NetworkHolder implements org.omg.CORBA.portable.Streamable
{
  public social_network_system.Social_Network value = null;

  public Social_NetworkHolder ()
  {
  }

  public Social_NetworkHolder (social_network_system.Social_Network initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = social_network_system.Social_NetworkHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    social_network_system.Social_NetworkHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return social_network_system.Social_NetworkHelper.type ();
  }

}
