package social_network_system;


/**
* social_network_system/Social_NetworkHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Social_Network.idl
* Saturday, March 30, 2013 1:35:55 AM IRDT
*/

abstract public class Social_NetworkHelper
{
  private static String  _id = "IDL:social_network_system/Social_Network:1.0";

  public static void insert (org.omg.CORBA.Any a, social_network_system.Social_Network that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static social_network_system.Social_Network extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (social_network_system.Social_NetworkHelper.id (), "Social_Network");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static social_network_system.Social_Network read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_Social_NetworkStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, social_network_system.Social_Network value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static social_network_system.Social_Network narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof social_network_system.Social_Network)
      return (social_network_system.Social_Network)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      social_network_system._Social_NetworkStub stub = new social_network_system._Social_NetworkStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static social_network_system.Social_Network unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof social_network_system.Social_Network)
      return (social_network_system.Social_Network)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      social_network_system._Social_NetworkStub stub = new social_network_system._Social_NetworkStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
